### ISSUE TITLE
Does it support PropertyInjection on handlers?

### ISSUE THREAD

**Issue by jehof** [alsami/MediatR.Extensions.Autofac.DependencyInjection#3]
I need to inject optional dependecies into my handlers (notification) through properties. Is this supported by your library

Autofac normally provides .PropertiesAutowired() for this case. 

        public class Handler : INotificationHandler<Created>
        {
            private IRepository _repository;

            public Handler (IRepository fleets)
            {
                _fleets = fleets;
            }

            //optional
            public ILogger<Handler > Logger { get; set; }

            public async Task Handle(Created notification, CancellationToken cancellationToken)
            {
                // work
            }
       }

**Comment by alsami** [comment]
Hi Jens,

as far as I understand this [documentation](https://autofaccn.readthedocs.io/en/latest/register/prop-method-injection.html) it won't work that way.

I am not calling `.PropertiesAutowired()` when registering the [open-generics](https://github.com/cleancodelabs/MediatR.Extensions.Autofac.DependencyInjection/blob/2.1.0/src/MediatR.Extensions.Autofac.DependencyInjection/MediatRModule.cs#L31).

However you can simply inject `ILogger<T>` and assign it to your property. `ILogger<T>` must be registered anyway, otherwise Autofac won't be able to construct it.

If that doesn't suite your requirements, please feel free to open a pull-request.

**Comment by jehof** [comment]
This sounds right and may not be supported by Autofac. I have added an additional ctor to my class to inject the logger and all things are fine.
